##1. One word at a time

In [10]:
import pandas as pd

text = ['cat', 'dog', 'fish', 'bird', 'cat', 'dog']

data = pd.get_dummies(text)

print(data)
print('-'*30)
print(data.keys())

    bird    cat    dog   fish
0  False   True  False  False
1  False  False   True  False
2  False  False  False   True
3   True  False  False  False
4  False   True  False  False
5  False  False   True  False
------------------------------
Index(['bird', 'cat', 'dog', 'fish'], dtype='object')


##2. Whole sentance at a time

In [12]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

text = ['i love dogs', 'i hate cats', 'i like turtles', 'i love the dogs']

text = np.reshape(text, (-1, 1))


encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)

print(one_hot.toarray())
print([i[3:]for i in encoder.get_feature_names_out()])

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
['i hate cats', 'i like turtles', 'i love dogs', 'i love the dogs']


##3. Tokenized Sentance

In [14]:
from sklearn.preprocessing import OneHotEncoder

text = [['this' ,'is' ,'good'], ['but','its','fine']]

encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)


print(one_hot.toarray())

print('-'*30)

print([i[3:]for i in encoder.get_feature_names_out()])

[[0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1. 0.]]
------------------------------
['but', 'this', 'is', 'its', 'fine', 'good']


In [16]:
pd.DataFrame(one_hot.toarray(), columns = [i[3:]for i in encoder.get_feature_names_out()])

,but,this,is,its,fine,good
0,0.0,1.0,1.0,0.0,0.0,1.0
1,1.0,0.0,0.0,1.0,1.0,0.0
